# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PoubelleConnecte' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PoubelleConnecte
  pod 'Alamofire'
  pod 'Charts', '3.0.0'
  pod 'CircleProgressView', :git => 'https://github.com/CardinalNow/iOS-CircleProgressView.git'

end
